### ISSUE TITLE
Layer not working in Keras 2.0.2

### ISSUE THREAD

**Issue by dburner** [drspiffy/Concurrence#1]
Hello, first of all thank you for sharing this. I have a problem using this layer. It gives me this error:

> ValueError: Shape must be rank 2 but is rank 3 for 'concurrence_1/MatMul_1' (op: 'MatMul') with input shapes: [?,?,128], [?,300].

I am using it like this:
```
model.add(EmbeddingWord2Vec())
model.add(GRU(128, return_sequences=True))
model.add(Concurrence())
model.add(RepeatVector(10))
model.add(GRU(128 * 2, return_sequences=True))
model.add(TimeDistributed(Dense(output_dim=256, activation="relu")))
```
Where EmbeddingWord2Vec adds a pretrained embedding layer that has the output shape of (None, 300, 128).

The problem occurs at  K.batch_dot(x, focus, (1, 1)), where x has a shape of (None, 300, 128) and focus has a shape of (None, 300).

**Comment by drspiffy** [comment]
Code has been updated for Keras version 2.

**Comment by dburner** [comment]
Thanks 👍
